name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '19.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
